insert into settings default values;

insert into exercises (name, category, equipment, default_sets, default_reps) values
  ('Leg Press', 'legs', 'machine', 3, 12),
  ('Leg Extension', 'legs', 'machine', 3, 12),
  ('Plank (sec)', 'core', 'bodyweight', 3, 30),
  ('Dumbbell Bench Press', 'push', 'dumbbells', 3, 10),
  ('Machine Shoulder Press', 'push', 'machine', 3, 10),
  ('Cable Triceps Pushdown', 'push', 'cable', 3, 12),
  ('Push-ups', 'push', 'bodyweight', 2, 12),
  ('Lat Pulldown', 'pull', 'cable', 3, 10),
  ('Seated Cable Row', 'pull', 'cable', 3, 10),
  ('Dumbbell Biceps Curl', 'pull', 'dumbbells', 3, 12),
  ('Cable Face Pull', 'pull', 'cable', 3, 15),
  ('Dead Bug', 'core', 'bodyweight', 3, 10);

insert into day_templates (position, name, exercise_ids, stretch_items)
select v.position, v.name,
       array(select e.id from unnest(v.names) with ordinality as n(name, ord) join exercises e on e.name = n.name order by n.ord),
       array['Stretching / mobility (5 min)']
from (values
  (1, 'Legs', array['Leg Press', 'Leg Extension', 'Plank (sec)']),
  (2, 'Upper - Push', array['Dumbbell Bench Press', 'Machine Shoulder Press', 'Cable Triceps Pushdown', 'Push-ups']),
  (3, 'Legs', array['Leg Press', 'Leg Extension', 'Plank (sec)']),
  (4, 'Upper - Pull + Core', array['Lat Pulldown', 'Seated Cable Row', 'Dumbbell Biceps Curl', 'Cable Face Pull', 'Dead Bug']),
  (5, 'Legs', array['Leg Press', 'Leg Extension', 'Plank (sec)'])
) as v(position, name, names);

insert into treadmill_templates (name, description, segments) values
  ('3-2-1', '3 min base, 2 min push, 1 min all out, 1 min walk. x3', '[{"sec": 180, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 180, "mode": "base", "incline": 1}, {"sec": 120, "mode": "push", "incline": 1}, {"sec": 60, "mode": "allout", "incline": 1}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 180, "mode": "base", "incline": 1}, {"sec": 120, "mode": "push", "incline": 1}, {"sec": 60, "mode": "allout", "incline": 1}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 180, "mode": "base", "incline": 1}, {"sec": 120, "mode": "push", "incline": 1}, {"sec": 60, "mode": "allout", "incline": 1}, {"sec": 60, "mode": "walk", "incline": 1}]'::jsonb),
  ('Incline Pyramid', 'Push up the incline hill and back down, then a base climb ladder', '[{"sec": 180, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 90, "mode": "push", "incline": 3}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 90, "mode": "push", "incline": 6}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "push", "incline": 9}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "push", "incline": 6}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "push", "incline": 3}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 90, "mode": "base", "incline": 2}, {"sec": 90, "mode": "base", "incline": 4}, {"sec": 90, "mode": "base", "incline": 6}, {"sec": 90, "mode": "base", "incline": 8}, {"sec": 90, "mode": "base", "incline": 6}, {"sec": 90, "mode": "base", "incline": 4}, {"sec": 90, "mode": "base", "incline": 2}]'::jsonb),
  ('Everest', 'Base climb +1% every minute to 12%, push back down, flat all-out finisher', '[{"sec": 180, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 60, "mode": "base", "incline": 2}, {"sec": 60, "mode": "base", "incline": 3}, {"sec": 60, "mode": "base", "incline": 4}, {"sec": 60, "mode": "base", "incline": 5}, {"sec": 60, "mode": "base", "incline": 6}, {"sec": 60, "mode": "base", "incline": 7}, {"sec": 60, "mode": "base", "incline": 8}, {"sec": 60, "mode": "base", "incline": 9}, {"sec": 60, "mode": "base", "incline": 10}, {"sec": 60, "mode": "base", "incline": 11}, {"sec": 60, "mode": "base", "incline": 12}, {"sec": 60, "mode": "push", "incline": 10}, {"sec": 60, "mode": "push", "incline": 8}, {"sec": 60, "mode": "push", "incline": 6}, {"sec": 60, "mode": "push", "incline": 4}, {"sec": 60, "mode": "push", "incline": 2}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 30, "mode": "walk", "incline": 1}]'::jsonb),
  ('Ascending Base Ladder', 'Base grows each round (30s to 2:30), push and all out stay the same', '[{"sec": 180, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 30, "mode": "base", "incline": 1}, {"sec": 60, "mode": "push", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 60, "mode": "push", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 90, "mode": "base", "incline": 1}, {"sec": 60, "mode": "push", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 120, "mode": "base", "incline": 1}, {"sec": 60, "mode": "push", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 150, "mode": "base", "incline": 1}, {"sec": 60, "mode": "push", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 60, "mode": "walk", "incline": 1}]'::jsonb),
  ('Power Day', 'Flat and fast: short all-outs, lots of them', '[{"sec": 180, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 45, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 45, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 45, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 45, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 45, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 45, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 45, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 45, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 30, "mode": "allout", "incline": 1}, {"sec": 45, "mode": "walk", "incline": 1}]'::jsonb),
  ('Endurance Day', 'Long sustained pushes, little incline change', '[{"sec": 180, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 240, "mode": "push", "incline": 2}, {"sec": 120, "mode": "base", "incline": 1}, {"sec": 240, "mode": "push", "incline": 2}, {"sec": 120, "mode": "base", "incline": 1}, {"sec": 240, "mode": "push", "incline": 2}, {"sec": 120, "mode": "base", "incline": 1}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 120, "mode": "push", "incline": 1}, {"sec": 60, "mode": "allout", "incline": 1}]'::jsonb),
  ('Hills (Strength Day)', 'Incline power: base at 5%, push at 8%, all out at 10%', '[{"sec": 180, "mode": "walk", "incline": 1}, {"sec": 60, "mode": "base", "incline": 1}, {"sec": 120, "mode": "base", "incline": 5}, {"sec": 90, "mode": "push", "incline": 8}, {"sec": 60, "mode": "allout", "incline": 10}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 120, "mode": "base", "incline": 5}, {"sec": 90, "mode": "push", "incline": 8}, {"sec": 60, "mode": "allout", "incline": 10}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 120, "mode": "base", "incline": 5}, {"sec": 90, "mode": "push", "incline": 8}, {"sec": 60, "mode": "allout", "incline": 10}, {"sec": 60, "mode": "walk", "incline": 1}, {"sec": 120, "mode": "base", "incline": 5}, {"sec": 90, "mode": "push", "incline": 8}, {"sec": 60, "mode": "allout", "incline": 10}, {"sec": 60, "mode": "walk", "incline": 1}]'::jsonb);
